name: Deploy App with Environment
on:
  pull_request:
    branches:
      - development
    types:
      - closed
jobs:
  deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Run Remote Commands
        env:
          DATABASE_HOST: ${{ secrets.DATABASE_HOST }}
          DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
          DATABASE_USER: ${{ secrets.DATABASE_USER }}
          DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
        run: |
          ssh -o StrictHostKeyChecking=no pronyr@12.144.172.20 << EOF
            cd /home/pronyr/lab2/secrets-and-actions-lab1
            git pull 
            touch .env
            echo DATABASE_HOST="DATABASE_HOST" >> .env
            echo DATABASE_NAME="DATABASE_NAME" >> .env
            echo DATABASE_USER="DATABASE_USER" >> .env
            echo DATABASE_PASSWORD="DATABASE_PASSWORD" >> .env                                  
            docker stop demo-app3
            docker rm demo-app3 
            docker build -t demo-app-image3 .
            docker run -d -t \
              -p 3000:3000 \
              --name demo-app3 \
              --env-file .env \
              demo-app-image3            
          EOF
